### ISSUE TITLE
Description of the "Extension" concept and the other concepts

### ISSUE THREAD

**Issue by ghost** [o2r-project/erc-spec#13]
It might be unclear to anyone new to ERC, how the extensions work and what is left, if no extension is used.  
The spec documentation should be updated to include a paragraph on this ("the extension concept") and reflect in its structure what is "base" and what is "extension".

**Comment by 7048730** [comment]
included in e03ef99ee2a006dcdaabfd316f7e2aeaf6ca295a
but still needs 
- [ ] update on elements/properties
- [ ] mark docs in o2r-meta as obsolete

**Comment by ghost** [comment]
Also "design concept" should not be part of the spec, but could form a new category where "the extension concept" might fit in.

**Comment by nuest** [comment]
Regarding "design concept" and clarification of extensions

- [ ] "Fundamental design concepts" should go into the dev guide, the spec is just facts and no arguing
- [ ] "Extensions" must be a top level section before "Nested runtime", extensions can do what they want but not break the core spec. Which extension is used in a specific ERC is visible by the required configured (as defined in the extension) being present within the ERC configuration file. (Metadata is still left in "ERC configuration file/Extension metada".)
- [ ] Add "extension" and "core" to the glossary.
- [ ] remove "core" from the core specification text (extensions may use the word to clarify...)

**Comment by nuest** [comment]
Extensions were already improved by #20

**Comment by ghost** [comment]
Extension concept will be dropped with current spec

**Comment by nuest** [comment]
See #36
