### ISSUE TITLE
Empty Affiliation Structure

### ISSUE THREAD

**Issue by jansule** [o2r-project/erc-spec#14]
Shouldn't the structure of an empty `affiliation` be an empty `array` instead of `null` as defined [here](https://github.com/o2r-project/erc-spec/blob/dea0b63e22e7b39297a2d372123a238ed6f7cecf/docs/spec/schema.md)?

This should be according to our definition and would provide a more consistent structure

**Comment by ghost** [comment]
fixed in docs in 57a62cbe68ecee0333babf19166ce0fce424b1e4
and in extractor.
