### ISSUE TITLE
Allow minimal ERC with only one plot

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#25]
I like the idea of allowing an ERC to contain only code for _one_ plot. I.e. an R-script `plot.R` and an output document `plot{.png,.pdf}`. The former could be the "main document" and the latter the "view document".

I suggest to make sure that the wording still allows this, i.e. that the main document CAN be a _script_ instead of a _literate programming file_.

If this should be possible, it would be nice to have an example minimal ERC like this, I think it would be easy for people to understand.

@7048730 Thoughts on this?

**Comment by ghost** [comment]
I think we talked about this once and I like the idea. I also think there might by good use cases for these kinds of publication as a type of "data publication with minimal visualization", i.e. there is no analysis, but  only code for figures.
Your suggestion to change the wording is one way to realise this, we could also start distinguishing the two cases of _analysis_ and _visualization_. But I guess it's not preferable to rely on the purpose of the code when constructing categories. On the other hand saying 
>the main document CAN be a script instead of a literate programming file.

invites the creator of an ERC to just ignore this suggestion.
