### ISSUE TITLE
Add reference to https://peerj.com/articles/cs-112/ to the user guide or reasoning for Rmd as core format

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#28]
https://peerj.com/articles/cs-112/

> Krewinkel A, Winkler R. (2017) Formatting Open Science: agilely creating multiple document formats for academic manuscripts with Pandoc Scholar. PeerJ Computer Science 3:e112 https://doi.org/10.7717/peerj-cs.112

**Comment by ghost** [comment]
main benefits of MD according to that paper are:

- longterm format interpretability (and handling of text versions through diff visualizations) using a simple syntax (standard markdown)
- contribution to an agile production of open science literature (less and simpler adjustments needed on the way to publication ready texts)
- metadata header (YAML / JSON-LD) for each document is a central aspect of open science

We could refer to these for our format reasoning and close the issue after adding
