### ISSUE TITLE
Add OAIS-related content to Archival extension

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#3]
See https://github.com/o2r-project/erc-spec/blob/master/docs/spec/archival.md#oais---under-development

**Comment by ghost** [comment]
- [x] add _information packages_ SIP, AIP, DIP
- [x] add _representation information_ role and context of interpretability of ERC

**Comment by ghost** [comment]
included with 7bfb2afdd993c8fded48d8165ccb45f80cef6dc9
