### ISSUE TITLE
ERC metadata as part of Rmd header

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#30]
RMarkdown headers are yaml, the `erc.yml` file is yaml - why not think about a variant of the ERC where the ERC metadata is actually in the header of the _main document_?

**Comment by ghost** [comment]
shouldn't the main document be untouched and aim for checksum identity with reproduced version? (or do you want to add ERC MD to both?)

**Comment by nuest** [comment]
good point.

no, I would not replicate the ERC MD.

so this is probably a bad idea.
