### ISSUE TITLE
Integrating expert feedback

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#31]
[These comments are based on notes and transcripts from a discussion of the ERC specification with publishing domain experts.]

- [x] dropping extensions is an excellent idea #36
- [x] a plain R solution is much smaller, consequently less burden for collaboration, but higher burden for preservation
- [x] need and option to download just main file and data (cf. https://github.com/o2r-project/o2r-platform/issues/26); _minimize footprint_ for specific usages
  - what would be the "dev version" of an ERC? everything but the runtime environment _image_? The Dockerfile, the RMarkdown document, and the data (explicitly)?
- ~~_community support is more important than technical support for people to be using the specification_~~
  - noted the _meta_-idea of a discussion forum, e.g. [discourse](https://github.com/discourse/discourse)
  - _not_ relevant for the spec
  - [x] add section to user guide (add email, add dicussion forum)
- [x] authors should not read the ERC spec, which is developer material; authors should be confronted with a very simple system within the submission experience; alternative: guide of required steps
- system must be as simple as possible, understandable by users if need be - _current state is really good_
- ~~**automated learning** should be considered for user experience, i.e. after an upload give feedback "you have 80% complete, consider these things", comparable to "profile completeness score"~~ > taken into consideration in UI only, not part of spec, rather an application of the spec
- ~~badges should be considered~~
  - ~~badges about ERC contents are imho out of scope, and badges for full ERC are under development, see https://github.com/o2r-project/o2r-badger (@nuest)~~
- two possibilities for UI bindings: RMarkdown + UI and write directly into RMarkdown; not being able to do the latter would be a drawback, "scientists don't like interactions" > deferred, see #32
- ~~evolutionary approach is favoured, i.e. not replacing the article completely but having one/multiple ERC as supplemental material~~

## Spec updates to be done

- [x] clarify the target audience for spec (devs, not authors) and guide (authors)
- [x] add reasoning against plain R solution to dev guide
- [x] how to handle ERC as supplemental material instead of the main published item? what metadata is (not) needed?
- [x] write concept for completeness score

**Comment by ghost** [comment]
updated

**Comment by nuest** [comment]
The comment on UI bindings are _not_ going to make it into the next iteration, see #32

**Comment by nuest** [comment]
@7048730 I think I've covered everything in this issue in https://github.com/o2r-project/erc-spec/commit/8d055fcd3feadbea5d3eafd044e9961aec681c18 - feedback welcome!

**Comment by nuest** [comment]
Contained in https://github.com/o2r-project/erc-spec/tree/post-workshop2017-update
