### ISSUE TITLE
Make use of Discover, Examine, Create on top level

### ISSUE THREAD

**Issue by ghost** [o2r-project/erc-spec#35]
We just discussed:

- Discover
- Examine
-- Check
-- Inspect
-- Manipilate
-- Substitute
- Create

as top level interactions and hence items for the spec.

Tasks for dev branch:

- [x] add terms to glossary
- [x] use check instead of validate in spec
- [x] replace "validation" with "bag validation" whenever this is meant, to avoid confusion

**Comment by nuest** [comment]
https://github.com/o2r-project/o2r-platform/issues/92

**Comment by nuest** [comment]
Completed in https://github.com/o2r-project/erc-spec/tree/post-workshop2017-update
