### ISSUE TITLE
We must clarify in the spec how to easily identify a BagIt bag as an ERC

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-spec#42]
Ideas (not necessarily conflicting):

- "open bag, look for `data/erc.yml`, if it exists, it's an ERC
- use mime type?
- use bag metadata, add field `Executable-Research-Compendium: Yes` to `bag-info.txt`

**Comment by ghost** [comment]
- open bag, look for data/erc.yml, **get id**, if it exists, it's an ERC
- mime type of which file(s)?
- bag-info.txt: `Is-Executable-Research-Compendium: True` -> that would be the outer most place to mark the ERC. I think, I would prefer that.

**Comment by nuest** [comment]
:+1: on the "get id" part in `erc.yml`.

Then suggest to got with

a) the bag-info.txt for **identification** (I also like it because implementations can simply `grep` that out of a plain text file), and _also_ 
b) the **there is an id in `erc.yml`** as part of the _checking process_ but not for identification (besides `erc.yml` being well-formed)

**Comment by ghost** [comment]
bag-info.txt is an optional file. The **bagit.txt** is required and is also the file that stores the version information of the bag. That one is what we want.

**Comment by nuest** [comment]
- [x] mention in the spec that implementations should use this approach
