### ISSUE TITLE
travis works but https://o2r.info/erc-spec/ content now gone..

### ISSUE THREAD

**Issue by mrustl** [o2r-project/erc-spec#73]
Website: https://o2r.info/erc-spec/

Travis: https://travis-ci.org/o2r-project/erc-spec/builds/437059246

Commit: https://github.com/o2r-project/erc-spec/commit/220767ddb5d0a7f561b4356e80206a447908bc8f

**Comment by mrustl** [comment]
site is back now....took only a while to update probably

**Comment by nuest** [comment]
Yes, I did some tinkering there... all back now.
